name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          .spago
          output
          node_modules
        key: build-artifacts-v1-${{ hashFiles('package-lock.json', 'spago.yaml', 'packages.yaml') }}

    - uses: actions/setup-node@v2
      with:
        node-version: 20

    - run: npm install
    - run: npx spago build

